# Infant Formula Comparison: Pipeline Walkthrough

This notebook traces the full pipeline from raw PDF extraction through cleaning to visualization.
All path resolution delegates to the installed `infant_formula` package — no hardcoded paths in notebook cells.

In [37]:
import json
import pandas as pd
import plotly.express as px
import openpyxl
import re


from infant_formula.collate import INPUTS_DIR, OUTPUTS_DIR, collate
from infant_formula.extract_pdf_tables import CONFIGS_DIR

## 1. Raw Extraction

`extract_pdf_tables.py` reads each PDF page-by-page and saves one CSV per page.
The naming convention is `{pdf_stem}_p{page}_t{table_index}.csv`.

In [18]:
csvs = sorted(OUTPUTS_DIR.glob("*_p*_t*.csv"))
print(f"{len(csvs)} page-level CSV files:\n")
for f in csvs:
    df_raw = pd.read_csv(f)
    print(f"  {f.name}: {df_raw.shape[0]} rows x {df_raw.shape[1]} cols")

5 page-level CSV files:

  Consumer-Reports-Baby-Formula-Test-Results-v4-March-2026_p1_t0.csv: 24 rows x 14 cols
  Consumer-Reports-Baby-Formula-Test-Results-v4-March-2026_p2_t0.csv: 22 rows x 14 cols
  Consumer-Reports-Baby-Formula-Test-Results-v4-March-2026_p3_t0.csv: 8 rows x 14 cols
  Consumer-Reports-Test-Results-Infant-Formula-v2_p1_t0.csv: 22 rows x 14 cols
  Consumer-Reports-Test-Results-Infant-Formula-v2_p2_t0.csv: 19 rows x 14 cols

In [19]:
# Peek at the first page's raw extracted content
pd.read_csv(csvs[0]).head(3)

,brand,model,total_arsenic,inorganic_arsenic,lead,cadmium,mercury,aluminum,potassium,bisphenol_a,bisphenol_f,bisphenol_s,acrylamide,report_year
0,POWDERED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026
1,Enfamil,Sensitive,10.6,9.0,1.8,ND,ND,272,"8,026,667",ND,ND,ND,ND,2026
2,Enfamil,Nutramigen with Probiotic\nLGG,8.4,7.6,5.7,2.1,ND,"2,187","6,970,000",8,ND,ND,12.0,2026

In [20]:
# Peek at the last page's raw extracted content to confirm that spaces are removed from brand names
pd.read_csv(csvs[0]).tail(6)

,brand,model,total_arsenic,inorganic_arsenic,lead,cadmium,mercury,aluminum,potassium,bisphenol_a,bisphenol_f,bisphenol_s,acrylamide,report_year
18,Mama Bear,Sensitivity Premium,3.6,NT,1.5,2.4,ND,"2,823","6,200,000",ND,ND,ND,ND,2026
19,Jovie,Stage 1 Organic Goat Milk,2.4,NT,1.9,ND,ND,706,"6,800,000",ND,ND,ND,ND,2026
20,Pure Bliss by\nSimilac,Irish Farms,3.5,NT,2.0,ND,0.7,587,"6,396,667",ND,ND,ND,ND,2026
21,Pure Goat,Bio Complete,ND,NT,2.1,2.5,ND,339,"6,790,000",ND,ND,ND,ND,2026
22,HiPP,Hypoallergenic,2.6,NT,1.9,3.3,ND,530,"6,300,000",ND,ND,ND,ND,2026
23,Holle,Organic Goat Milk,2.1,NT,2.1,3.3,ND,206,"6,500,000",ND,ND,ND,ND,2026

## 2. Column Configuration

The PDFs have rotated column headers that pdfplumber reads top-to-bottom (reversing each character).
`inspect_header_row()` decodes them and writes a JSON template to `configs/` for human review.
The final column names used in extraction come from these edited config files.

In [21]:
for cfg in sorted(CONFIGS_DIR.glob("*_columns.json")):
    if "original" in cfg.name:
        continue
    cols = json.loads(cfg.read_text())
    print(f"{cfg.name}:")
    for i, col in enumerate(cols):
        print(f"  {i:2d}: {col}")
    print()

Consumer-Reports-Baby-Formula-Test-Results-v4-March-2026_columns.json:
   0: brand
   1: model
   2: total_arsenic
   3: inorganic_arsenic
   4: lead
   5: cadmium
   6: mercury
   7: aluminum
   8: potassium
   9: bisphenol_a
  10: bisphenol_f
  11: bisphenol_s
  12: acrylamide

Consumer-Reports-Test-Results-Infant-Formula-v2_columns.json:
   0: brand
   1: model
   2: total_arsenic
   3: inorganic_arsenic
   4: lead
   5: cadmium
   6: mercury
   7: aluminum
   8: potassium
   9: bisphenol_a
  10: bisphenol_f
  11: bisphenol_s
  12: acrylamide

## 3. Collation & Cleaning

`collate()` does three things:
1. Concatenates all per-page CSVs into one dataframe
2. Strips thousands-separator commas from numeric strings (e.g. `"8,026,667"` → `"8026667"`)
3. Drops subheader rows (e.g. `"POWDERED"`, `"LIQUID"`) that have no `model` value

The cell below captures a raw value before `collate()` runs, then checks the cleaned version after.

In [22]:
# Skip subheader rows (e.g. "POWDERED") — they have no model value and are dropped by collate()
first_page = pd.read_csv(csvs[0])
first_data_row = first_page[first_page["model"].notna()].iloc[0]
sample_brand = first_data_row["brand"]
raw_potassium = first_data_row["potassium"]
print(f"Raw (from page CSV)  — brand: {sample_brand!r}, potassium: {raw_potassium!r}")

Raw (from page CSV)  — brand: 'Enfamil', potassium: '8,026,667'

In [23]:
collate()

collated = pd.read_csv(OUTPUTS_DIR / "all_formula.csv")
cleaned_row = collated[collated["brand"] == sample_brand].iloc[0]
print(f"After collate()      — brand: {cleaned_row['brand']!r}, potassium: {cleaned_row['potassium']!r}")
print(f"\nCollated shape: {collated.shape}")
collated.head(3)

Saved 90 rows to /Users/sarahfouzia/llm_workspace/repos/infant_formula_comparison/outputs/all_formula.csv
After collate()      — brand: 'Enfamil', potassium: '8,026,667'

Collated shape: (90, 14)

,brand,model,total_arsenic,inorganic_arsenic,lead,cadmium,mercury,aluminum,potassium,bisphenol_a,bisphenol_f,bisphenol_s,acrylamide,report_year
0,Enfamil,Sensitive,10.6,9.0,1.8,ND,ND,272,"8,026,667",ND,ND,ND,ND,2026
1,Enfamil,Nutramigen with Probiotic\nLGG,8.4,7.6,5.7,2.1,ND,2187,"6,970,000",8,ND,ND,12.0,2026
2,Dr. Brown’s,Good Start Soy-Ease Pro,9.9,7.9,2.3,4.3,0.5,4403,"6,806,667",ND,ND,ND,ND,2026

## 4. Input table enriched with website_link and ingredient_list

`all_formula_ingredients_manual_entry.csv`is a table with two additional columns for 'website_link' and 'ingredient_list'

Added those two columns manually as different brands render their ingredient lists differently

Using df for the output from this extraction and df_website_ingredients for the file with the links i.e. `all_formula_ingredients_manual_entry.csv`

The main reason for doing this is to keep the extraction step separate from the manual entry step. For example, if there are additional formulas tested next year, it would be better to join the existing df_website_ingredients with the additional entries from the extraction step in df. The current dataset has the chemical analyses from 2025 and 2026

In [24]:
df_website_ingredients = pd.read_excel(INPUTS_DIR / "all_formula_ingredients_manual_entry.xlsx")
print(df_website_ingredients.head(15))
print(df_website_ingredients.tail(15))

    index_100                 brand                                model  \
0         101                    A2                             Platinum
1         102               Aptamil                    First Infant Milk
2         103  Baby’s Only\nOrganic                   Complete Nutrition
3         104                Bobbie  Grass-Fed Whole Milk\n(non-organic)
4         105                Bobbie                              Organic
5         106                Bobbie                       Organic Gentle
6         107                Bobbie                   Organic Whole Milk
7         108                  Bubs       Stage 1 Easy-digest\nGoat Milk
8         109                  Bubs           Stage 1 Organic\nGrass Fed
9         110               ByHeart                      Whole Nutrition
10        111           Dr. Brown’s                            GentlePro
11        112           Dr. Brown’s              Good Start Soy-Ease Pro
12        113           Dr. Brown’s                            SoothePro
13        114          Earth’s Best                        Organic Dairy
14        115          Earth’s Best                  Organic Sensitivity

                                                                                                           website_link  \
0                                                                                   https://a2platinum.com/pages/why-a2
1                       https://www.nutricia.co.uk/hcp/pim-products/aptamil-first-infant-milk-with-pronutra-powder.html
2                                     https://babysonly.com/collections/shop-all/products/organic-gentle-infant-formula
3                   https://www.hibobbie.com/products/grass-fed-whole-milk-infant-formula-14-1oz?variant=42520514101333
4                                https://www.hibobbie.com/products/bobbie-organic-infant-formula?variant=42520534450261
5                         https://www.hibobbie.com/products/bobbie-organic-gentle-infant-formula?variant=42520529928277
6                                                   https://www.hibobbie.com/products/organic-whole-milk-infant-formula
7                                          https://www.bubsaustralia.com/products/bubs-goat-milk-infant-formula-s1-800g
8                                        https://www.bubsaustralia.com/products/bubs-organic-infant-formula-s1-800g-x-1
9   https://www.samsclub.com/ip/byheart-whole-nutrition-powder-infant-formula-for-0-12-months-24oz-canister/17596850186
10                       https://www.goodstartbaby.com/products/gentle-pro-infant-formula-powder?variant=49188795384117
11                     https://www.goodstartbaby.com/products/soy-ease-pro-infant-formula-powder?variant=49188736008501
12                       https://www.goodstartbaby.com/products/soothe-pro-infant-formula-powder?variant=49188804755765
13                                                      https://www.earthsbest.com/products/dairy-infant-formula-23-2oz
14                                                https://www.earthsbest.com/products/sensitivity-infant-formula-23-2oz

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ingredient_list  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               recalled
1                                                                                                                                                                                                                                                         Dairy-based blend (of which 29% is fermented) [Lactose (from milk), Vegetable oils (High oleic sunflower oil, Coconut oil, Rapeseed oil, Sunflower oil), Skimmed milk, Demineralised whey (from milk), Whey concentrate (from milk), Fish oil, Potassium citrate, Calcium carbonate, Magnesium chloride, Choline chloride, Calcium phosphate, Sodium citrate, Potassium chloride, Vitamin C, Emulsifier (Soy lecithin), Inositol, Antioxidant (Vitamin C), Pantothenic acid, Nicotinamide, Vitamin E, Thiamin, Riboflavin, Vitamin B₆, Potassium iodide, Folic acid, Vitamin K₁, Biotin, Vitamin B₁₂], Galacto-oligosaccharides (GOS) (from milk), Milk protein, Fructo-oligosaccharides (FOS), Oil from Mortierella Alpina, Sodium chloride, L-Tryptophan, Ferrous sulphate, Zinc sulphate, L-Carnitine, Copper sulphate, Vitamin A, Sodium selenite, Manganese sulphate, Vitamin D₃. Allergy Advice: For allergens, see ingredients in bold.
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Organic Lactose, Organic Nonfat Milk (Source Of A2 Proteins), Organic High Oleic Sunflower, Organic Soybean Oil, Organic Whey Protein Concentrate, Organic Coconut Oil, Less Than 2% Of: Organic Soy Lecithin, Calcium Carbonate, Calcium Phosphate, Sodium Chloride, Potassium Chloride, Potassium Citrate, Magnesium Phosphate, Choline Bitartrate, Calcium Ascorbate, Inositol, Ferrous Sulfate, D-Alpha Tocopheryl Acetate, Zinc Sulfate, Niacinamide, Calcium Pantothenate, Biotin, Vitamin A, Thiamin Hydrochloride, Copper Sulfate, Riboflavin, Pyridoxine Hydrochloride, Sodium Selenate, Manganese Sulfate, Phylloquinone, Folic Acid, Vitamin D3, And Vitamin B12.
3                                                                                                                                                                                                                                                                            lactose, organic whole milk, organic linoleic sunflower oil, organic low erucic acid rapeseed oil, organic whey protein concentrate, organic high oleic sunflower oil, organic coconut oil, less than 2 % of: organic low erucic acid rapeseed lecithin, schizochytrium sp. oil*, mortierella alpina oil**, calcium carbonate, calcium phosphate, potassium chloride, sodium chloride, potassium citrate, l-carnitine, magnesium phosphate, calcium ascorbate, choline bitartrate, inositol, potassium iodide, ferrous sulfate, d-alpha tocopheryl acetate, zinc sulfate, vitamin c palmitate, niacinamide, calcium pantothenate, biotin, vitamin a, thiamin hydrochloride, copper sulfate, riboflavin, mixed tocopherols, pyridoxine hydrochloride, sodium selenate, manganese sulfate, phylloquinone, folic acid, vitamin d3, vitamin b12. * a source of docosahexaenoic acid (dha) ** a source of arachidonic acid (ara)
4                                                                                                          organic lactose, organic nonfat milk, organic high oleic (safflower or sunflower) oil, organic low erucic acid rapeseed oil, organic whey protein concentrate, organic coconut oil, organic linoleic (sunflower or safflower) oil, less than 1%: organic low erucic acid rapeseed lecithin, schizochytrium sp. oil; mortierella alpina oil;" calcium phosphate, potassium citrate, sodium chloride, calcium carbonate, potassium hydroxide, potassium phosphate, magnesium chloride, potassium bicarbonate, ferrous sulfate, potassium chloride, zinc sulfate, cupric sulfate, manganese sulfate, potassium iodide, sodium selenite, choline bitartrate, ascorbic acid (vitamin c), ascorbyl palmitate, inositol, l-carnitine, mixed tocopherols concentrate, di-alpha tocopheryl acetate (vitamin e), niacinamide (vitamin b3), calcium pantothenate, vitamin a palmitate, riboflavin (vitamin b2), thiamine hydrochloride (vitamin b1), pyridoxine hydrochloride (vitamin b6), folic acid, phytonadione (vitamin k), biotin, cholecalciferol (vitamin d3), cyanocobalamin (vitamin b12).' '
5    organic lactose, organic partially hydrolyzed whey protein, organic high oleic (safflower or sunflower) oil, organic low erucic acid rapeseed oil, organic coconut oil, organic linoleic (safflower or sunflower) oil, less than 1%: organic low erucic acid rapeseed lecithin, mortierella alpina oil**, schizochytrium sp. oil***, vitamin a palmitate, cholecalciferol (vitamin d3), d/-alpha tocopheryl acetate (vitamin e), mixed tocopherols concentrate, phytonadione (vitamin k), ascorbyl palmitate, thiamine hydrochloride (vitamin b1), riboflavin (vitamin b2), pyridoxine hydrochloride (vitamin b6), cyanocobalamin (vitamin b12), niacinamide (vitamin b3), folic acid, calcium pantothenate, biotin, ascorbic acid (vitamin c), choline bitartrate, inositol, l-carnitine, calcium carbonate, calcium chloride, calcium hydroxide, calcium phosphate, ferrous sulfate, zinc sulfate, manganese sulfate, cupric sulfate, magnesium chloride, potassium bicarbonate, potassium chloride, potassium phosphate, potassium hydroxide, potassium iodide, sodium chloride, sodium selenite, sodium citrate. **a source of arachidonic acid (ara) ***a source of docosahexaenoic acid (dha)
6                                                                                                                                                                                                                                                                                                                                                    organic lactose, organic whole milk, organic linoleic sunflower oil, organic low erucic acid rapeseed oil, organic whey protein concentrate, organic high oleic sunflower oil, organic coconut oil, less than 2 % of: organic low erucic acid rapeseed lecithin, schizochytrium sp. oil* mortierella alpina oil**, calcium carbonate, calcium phosphate, potassium chloride, sodium chloride, potassium citrate, l-carnitine, magnesium phosphate, calcium ascorbate, choline bitartrate, inositol, potassium iodide, ferrous sulfate, d-alpha tocopheryl acetate, zinc sulfate, vitamin c palmitate, niacinamide, calcium pantothenate, biotin, vitamin a, thiamin hydrochloride, copper sulfate, riboflavin, mixed tocopherols, pyridoxine hydrochloride, sodium selenate, manganese sulfate, phylloquinone, folic acid, vitamin d3, vitamin b12.
7                                                                                                                                                                                                                                                 Lactose, Goat Milk Solids (Goat Full Cream Milk Solids, Goat Whey Protein Concentrate) 28%, Vegetable Oil Blend (Sustainable Palm Olein, High Oleic Sunflower Oil, Canola Oil, Sunflower Oil, Coconut Oil), Galacto-Oligosaccharide (GOS), Docosahexaenoic Acid (DHA, From Alage), Emulsifier (Soybean Lecithin), Arachidonic Acid (ARA), Choline Bitartrate, Inositol, Taurine, Antioxidants (α-Tocopherol, Ascorbyl Palmitate), L-Carnitine. Vitamins: Sodium Ascorbate, dl-α-Tocopheryl Acetate, Vitamin A Acetate, Niacinamide, Calcium Pantothenate, Cyanocobalamin, Cholecalciferol, d-Biotin, Folic Acid, Phytonadione, Thiamine Hydrochloride, Riboflavin, Pyridoxine Hydrochloride. Minerals: Sodium Citrate, Calcium Carbonate, Potassium Chloride, Ferrous Sulphate, Magnesium Sulphate, Magnesium Chloride, Calcium Phosphate, Zinc Sulphate, Copper Sulphate, Manganese Sulphate, Potassium Iodide, Potassium Phosphate, Sodium Selenite.
8                                                                                                                                                                                                                                                                                                                                    Organic Lactose, Organic Vegetable Oil Blend (High Oleic Sunflower, Coconut, Soy, Canola), Organic Whole Milk Powder, Organic Whey Protein Concentrate, Organic Skim Milk Powder, Organic Galacto-Oligosaccharide (GOS), Emulsifier (Soy Lecithin), Docosahexaenoic Acid (DHA, from Algae), Arachidonic Acid (ARA), Probiotic Bifidobacterium longum BB536. Vitamins: Ascorbic Acid, dl-α-Tocopheryl Acetate, Vitamin A Acetate, Niacinamide, Calcium Pantothenate, Cholecalciferol, Thiamine Hydrochloride, Cyanocobalamin, Phytonadione, Pyridoxine Hydrochloride, Folic Acid, D-Biotin Minerals: Potassium Phosphate, Calcium Phosphate, Magnesium Chloride, Sodium Chloride, Calcium Carbonate, Potassium Chloride, Ferrous Sulphate, Potassium Citrate, Sodium Citrate, Zinc Sulphate, Copper Sulphate, Manganese Sulphate, Potassium Iodide, Sodium Selenite.
9                                                                           "ORGANIC WHOLE MILK*, LACTOSE, ORGANIC VEGETABLE OILS (ORGANIC HIGH OLEIC SUNFLOWER, ORGANIC, LOW ERUCIC RAPESEED, ORGANIC COCONUT, ORGANIC SUNFLOWER), ORGANIC GALACTOOLIGOSACCHARIDES°, ALPHA-LACTALBUMIN ** WHEY PROTEIN, WHEY PROTEIN HYDROLYSATE, LESS THAN 1%: LACTOFERRIN *** , DHA ALGAL OIL8 (SCHIZOCHYTRIUM), MORTIERELLA ALPINA OIL*, VITAMIN A PALMITATE, VITAMIN D3, VITAMIN E ACETATE, VITAMIN K1, THIAMINE HYDROCHLORIDE, RIBOFLAVIN, VITAMIN B6 HYDROCHLORIDE, VITAMIN B12, NIACINAMIDE, CALCIUM PANTOTHENATE, FOLIC ACID, BIOTIN, ASCORBIC ACID, MIXED TOCOPHEROLS, ASCORBYL PALMITATE, L-CARNITINE, INOSITOL, CALCIUM PHOSPHATE, SODIUM CITRATE, CALCIUM CARBONATE, POTASSIUM CITRATE, FERROUS SULFATE, POTASSIUM CHLORIDE, MAGNESIUM PHOSPHATE, CALCIUM CHLORIDE, ZINC SULFATE, CUPRIC SULFATE, MANGANESE SULFATE, POTASSIUM IODIDE, SODIUM SELENATE, POTASSIUM BICARBONATE, CHOLINE CHLORIDE. CONTAINS: MILK *FIRST US INFANT FORMULA TO INCLUDE ORGANIC, GRASS-FED WHOLE MILK ** FIRST US INFANT FORMULA AT BREAST MILK LEVELS *** A KEY PROTEIN FOUND IN BREAST MILK AND COLOSTRUM °A PREBIOTIC FIBER"
10                                                                                                                                                          Ingredients: Whey Protein Concentrate (From Milk, Enzymatically Hydrolyzed, Reduced In Minerals), Vegetable Oils (Palm Olein, Soy, Coconut, High Oleic Safflower or High Oleic Sunflower), Lactose, Corn Maltodextrin, and Less Than 2% of: Potassium Hydroxide, Calcium Chloride, Potassium Phosphate, Calcium Phosphate, Choline Bitartrate, 2'-O-Fucosyllactose, Citric Acid, M. Alpina Oil, Schizochytrium Oil, Sodium Ascorbate, Magnesium Chloride, Sodium Citrate, Soy Lecithin, Taurine, Nucleotides (Cytidine 5'-Monophosphate, Disodium Uridine 5'-Monophosphate, Adenosine 5'-Monophosphate, Disodium Guanosine 5'-Monophosphate), Inositol, Ferrous Sulfate, Alpha-Tocopheryl Acetate, Mixed Tocopherols, Ascorbyl Palmitate, Zinc Sulfate, Niacinamide, Calcium Pantothenate, B. lactis cultures, L-Carnitine, Copper Sulfate, Riboflavin, Thiamine Mononitrate, Vitamin A Acetate, Pyridoxine Hydrochloride, Manganese Sulfate, Potassium Iodide, Folic Acid, Phylloquinone, Biotin, Sodium Selenate, Vitamin D3, Vitamin B12.
11                                                                                                                                                                                                                                   Ingredients: Corn Syrup, Soy Protein Isolate, Palm Olein, Soy Oil, Coconut Oil, High Oleic (Safflower or Sunflower) Oil, and Less Than 2% of: Mortierella Alpina Oil, Schizochytrium Sp. Oil, Lutein, Fructooligosaccharide, Calcium Phosphate, Potassium Citrate, Potassium Chloride, Magnesium Chloride, Sodium Citrate, Ascorbic Acid, Choline Bitartrate, L-Methionine, Taurine, Ascorbyl Palmitate, Ferrous Sulfate, Inositol, Mixed Tocopherol Concentrate, Zinc Sulfate, Vitamin E (dl-Alpha Tocopheryl Acetate), L-Carnitine, Niacinamide, Calcium Pantothenate, Cupric Sulfate, Thiamine Hydrochloride, Vitamin A Palmitate, Riboflavin, Pyridoxine Hydrochloride, Folic Acid, Potassium Iodide, Potassium Hydroxide, Vitamin K (Phytonadione), Biotin, Sodium Selenite, Beta-Carotene, Vitamin D (Cholecalciferol), Cyanocobalamin, Monoglycerides, Soy Lecithin, Tribasic Calcium Phosphate, Calcium Carbonate, Manganese Sulfate, Potassium Bicarbonate
12                                                                                                                                           Ingredients: Corn Maltodextrin, Whey Protein Concentrate (From Milk, Enzymatically Hydrolyzed, Reduced in Minerals), Vegetable Oils (Palm Olein, Soy, Coconut, High Oleic Safflower or High Oleic Sunflower), and Less than 2% of: Potassium Hydroxide, Calcium Chloride, Potassium Phosphate, Calcium Phosphate, Citric Acid, Choline Bitartrate, 2'-O-Fucosyllactose, M. Alpina Oil, Schizochytrium Oil, Sodium Ascorbate, Magnesium Chloride, Sodium Citrate, Lactobacillus reuteri (Dsm 17938) Cultures, Soy Lecithin, Taurine, Nucleotides (Cytidine 5'-Monophosphate, Disodium Uridine 5'-Monophosphate, Adenosine 5'-Monophosphate, Disodium Guanosine 5'-Monophosphate), Inositol, Ferrous Sulfate, Alpha-Tocopheryl Acetate, Ascorbyl Palmitate, Mixed Tocopherols, Zinc Sulfate, Niacinamide, Calcium Pantothenate, L-Carnitine, Copper Sulfate, Vitamin A Acetate, Riboflavin, Thiamine Mononitrate, Pyridoxine Hydrochloride, Manganese Sulfate, Potassium Iodide, Folic Acid, Phylloquinone, Biotin, Sodium Selenate, Vitamin D3, Vitamin B12.

In [25]:
# conversion from xlsx file to csv during manual entry didn't work
# df_website_ingredients = pd.read_csv(INPUTS_DIR / "all_formula_ingredients_manual_entry.csv")
# print(f"Shape: {df_website_ingredients.shape}\n")
# df_website_ingredients.dtypes

In [42]:
df = pd.read_csv(OUTPUTS_DIR / "all_formula.csv")
print(f"Shape: {df.shape}\n")
df.dtypes

Shape: (90, 14)

brand                  str
model                  str
total_arsenic          str
inorganic_arsenic      str
lead                   str
cadmium                str
mercury                str
aluminum               str
potassium              str
bisphenol_a            str
bisphenol_f            str
bisphenol_s            str
acrylamide             str
report_year          int64
dtype: object

## 5. Left Join df with df_website_ingredients on brand and model

In [43]:
df = df.merge(
      df_website_ingredients[["brand", "model", "report_year", "website_link", "ingredient_list"]],
      on=["brand", "model", "report_year"],
      how="left",
  ).sort_values(["brand","model"]).reset_index(drop=True)

In [44]:
df.head()
df.tail()

,brand,model,total_arsenic,inorganic_arsenic,lead,cadmium,mercury,aluminum,potassium,bisphenol_a,bisphenol_f,bisphenol_s,acrylamide,report_year,website_link,ingredient_list
85,Sprout Organics,Plant-Based,15.1,4.5,8.5,22.4,1.6,4463,"5,166,667",3,ND,ND,18,2026,https://sproutorganic.com.au/products/infant-formula,"Organic Hydrolysed Rice Starch, Organic Oil Blend (Organic Coconut Oil, Organic Canola Oil, Organic Sunflower Oil, emulsifier organic sunflower lecithin, antioxidant natural mixed tocopherols), Sprout Organic Protein Blend (Organic Sprouted Rice Protein, Organic Sprouted Pea Protein), Docosahexaenoic Acid (DHA from algae), Arachidonic Acid (ARA from fungal), Vitamins, Minerals & Amino Acid Mix (Potassium, Calcium, Chloride, Phosphorus, L-Lysine, Choline, Sodium, Inositol, Vitamin C, L-Tryptophan, L-Threonine, Magnesium, Iron, Niacin, L-carnitine, Zinc, Vitamin E, Pantothenic Acid, Vitamin A, Riboflavin, Copper, Thiamin, Vitamin B6, Folic Acid, Manganese, Vitamin K1, Iodine, Biotin, Selenium, Vitamin D2, Vitamin B12)."
86,Up&Up (Target),Hypoallergenic,7.4,5.9,2.1,ND,ND,448,"7,673,333",ND,ND,ND,ND,2026,https://www.target.com/p/non-gmo-hypoallergenic-powder-infant-formula-27-8oz-up-38-up-8482/-/A-85428762,"corn syrup solids, vegetable oils (palm olein, soy, coconut, high oleic (safflower or sunflower) oil), casein hydrolysate (from milk)+, modified corn starch, less than 2%: mortierella alpina oil, schizochytrium sp. oil, lactobacillus rhamnosus, beta-carotene, vitamin a palmitate, vitamin d3, vitamin e acetate, vitamin k1, thiamin hydrochloride, riboflavin, vitamin b6 hydrochloride, vitamin b12, niacinamide, folic acid, calcium pantothenate, biotin, ascorbic acid, choline bitartrate, inositol, calcium citrate, calcium hydroxide, calcium phosphate, magnesium chloride, ferrous sulfate, zinc sulfate, manganese sulfate, cupric sulfate, potassium iodide, sodium selenite, sodium citrate, potassium citrate, potassium chloride, potassium bicarbonate, l-cystine, l-tryptophan, taurine, l-carnitine, calcium carbonate, calcium chloride, potassium hydroxide, potassium phosphate, ascorbyl palmitate, mixed tocopherol concentrate. ‡a source of hypoallergenic protein *a source of arachidonic acid (ara) **a source of docosahexaenoic acid (dha)"
87,Up&Up (Target),Premium,ND,NT,ND,ND,ND,191,"7,005,000",ND,ND,ND,ND,2025,https://www.target.com/p/premium-powder-infant-formula-22-2oz-up-38-up-8482/-/A-87841478,"nonfat milk, lactose, vegetable oils (palm olein, soy, coconut, high oleic [safflower or sunflower] oil), whey protein concentrate, less than 1%: 2'-fucosyllactose (2'-fl)◊, mortierella alpina oil*, schizochytrium sp. oil**, soy lecithin, vitamin a palmitate, vitamin d3, vitamin e acetate, vitamin k ,, thiamine hydrochloride, riboflavin, vitamin b; hydrochloride, vitamin b12, niacinamide, folic acid, calcium pantothenate, biotin, ascorbic acid, choline bitartrate, inositol, calcium carbonate, calcium chloride, calcium hydroxide, magnesium chloride, ferrous sulfate, zinc sulfate, manganese sulfate, cupric sulfate, potassium bicarbonate, potassium iodide, potassium hydroxide, potassium phosphate, sodium selenite, sodium citrate, taurine, l-carnitine, beta-carotene, mixed tocopherol concentrate, ascorbyl palmitate, monoglycerides, nucleotides (cytidine-5'-monophosphate, disodium uridine-5'-monophosphate, adenosine-5'-monophosphate, disodium guanosine-5'-monophosphate)."
88,Up&Up (Target),Sensitivity Premium,5.7,5.0,1.8,ND,ND,1585,"5,593,333",ND,ND,ND,ND,2026,https://www.target.com/p/sensitivity-premium-infant-formula-with-iron-powder-22-5oz-up-38-up-8482/-/A-85428763,"corn syrup, milk protein isolate, high oleic (safflower or sunflower) oil, sucrose, soy oil, coconut oil, less than 2%: mortierella alpina oil *, schizochytrium sp. oil **, 2'-fucosyllactose (2'-fl)º, lacto-n-neotetraose (lnnt)0, lutein, calcium phosphate, potassium citrate, potassium chloride, sodium citrate, magnesium phosphate, ascorbic acid, calcium carbonate, ferrous sulfate, magnesium chloride, ascorbyl palmitate, choline bitartrate, taurine, inositol, vitamin e (di-alpha tocopheryl acetate), zinc sulfate, mixed tocopherol concentrate, l-carnitine, niacin (niacinamide), calcium pantothenate, vitamin a palmitate, cupric sulfate, thiamine hydrochloride, riboflavin, pyridoxine hydrochloride, beta-carotene, folic acid, manganese sulfate, potassium iodide, vitamin k (phytonadione), biotin, sodium selenite, vitamin d (cholecalciferol), cyanocobalamin, potassium hydroxide, potassium bicarbonate, sodium chloride, sodium phosphate, monoglycerides, soy lecithin, nucleotides (adenosine-5'-monophosphate, cytidine-5'-monophosphate, disodium guanosine-5'-monophosphate, disodium uridine-5'-monophosphate). contains milk and soy."
89,Up&Up (Target),Soy,6.7,5.3,3.4,4.6,ND,3680,"6,460,000",ND,ND,ND,ND,2025,https://www.target.com/p/soy-powder-infant-formula-36oz-up-38-up-8482/-/A-15118125,"corn syrup, soy protein isolate, palm olein, soy oil, coconut oil, high oleic (safflower or sunflower) oil, less than 2%: mortierella alpina oil*, schizochytrium sp. oil**, lutein, fructooligosaccharide, calcium phosphate, potassium citrate, potassium chloride, magnesium chloride, sodium citrate, ascorbic acid, choline bitartrate, l-methionine, taurine, ascorbyl palmitate, ferrous sulfate, inositol, mixed tocopherol concentrate, zinc sulfate, vitamin e (di-alpha tocopheryl acetate), l-carnitine, niacinamide, calcium pantothenate, cupric sulfate, thiamine hydrochloride, vitamin a palmitate, riboflavin, pyridoxine hydrochloride, folic acid, potassium iodide, potassium hydroxide, vitamin k (phytonadione), biotin, sodium selenite, beta-carotene, vitamin d (cholecalciferol), cyanocobalamin, monoglycerides, soy lecithin, tribasic calcium phosphate, calcium carbonate, manganese sulfate, potassium bicarbonate. * a source of arachidonic acid (ara) ** a source of docosahexaenoic acid (dha)"

In [45]:
df_xlsx = pd.read_excel(INPUTS_DIR / "all_formula_ingredients_manual_entry.xlsx")
df_xlsx.dtypes

index_100              int64
brand                    str
model                    str
website_link             str
ingredient_list          str
has_soy              float64
has_palm_oil         float64
total_arsenic         object
inorganic_arsenic     object
lead                  object
cadmium               object
mercury               object
aluminum              object
potassium              int64
bisphenol_a           object
bisphenol_f              str
bisphenol_s              str
acrylamide            object
report_year            int64
dtype: object

## 6. Add an index starting from 100 on the left
This makes it easier to find the records in alphabetical order

In [46]:
df.insert(0,'index_100', range(101, 101+ len(df)))

In [47]:
df.head()

,index_100,brand,model,total_arsenic,inorganic_arsenic,lead,cadmium,mercury,aluminum,potassium,bisphenol_a,bisphenol_f,bisphenol_s,acrylamide,report_year,website_link,ingredient_list
0,101,A2,Platinum,ND,NT,2.9,ND,ND,1770,"5,580,000",ND,ND,ND,ND,2025,https://a2platinum.com/pages/why-a2,recalled
1,102,Aptamil,First Infant Milk,ND,NT,1.5,ND,ND,215,"5,670,000",ND,ND,ND,ND,2025,https://www.nutricia.co.uk/hcp/pim-products/aptamil-first-infant-milk-with-pronutra-powder.html,"Dairy-based blend (of which 29% is fermented) [Lactose (from milk), Vegetable oils (High oleic sunflower oil, Coconut oil, Rapeseed oil, Sunflower oil), Skimmed milk, Demineralised whey (from milk), Whey concentrate (from milk), Fish oil, Potassium citrate, Calcium carbonate, Magnesium chloride, Choline chloride, Calcium phosphate, Sodium citrate, Potassium chloride, Vitamin C, Emulsifier (Soy lecithin), Inositol, Antioxidant (Vitamin C), Pantothenic acid, Nicotinamide, Vitamin E, Thiamin, Riboflavin, Vitamin B₆, Potassium iodide, Folic acid, Vitamin K₁, Biotin, Vitamin B₁₂], Galacto-oligosaccharides (GOS) (from milk), Milk protein, Fructo-oligosaccharides (FOS), Oil from Mortierella Alpina, Sodium chloride, L-Tryptophan, Ferrous sulphate, Zinc sulphate, L-Carnitine, Copper sulphate, Vitamin A, Sodium selenite, Manganese sulphate, Vitamin D₃. Allergy Advice: For allergens, see ingredients in bold."
2,103,Baby’s Only\nOrganic,Complete Nutrition,ND,NT,1.4,ND,ND,307,"6,080,000",ND,ND,ND,ND,2025,https://babysonly.com/collections/shop-all/products/organic-gentle-infant-formula,"Organic Lactose, Organic Nonfat Milk (Source Of A2 Proteins), Organic High Oleic Sunflower, Organic Soybean Oil, Organic Whey Protein Concentrate, Organic Coconut Oil, Less Than 2% Of: Organic Soy Lecithin, Calcium Carbonate, Calcium Phosphate, Sodium Chloride, Potassium Chloride, Potassium Citrate, Magnesium Phosphate, Choline Bitartrate, Calcium Ascorbate, Inositol, Ferrous Sulfate, D-Alpha Tocopheryl Acetate, Zinc Sulfate, Niacinamide, Calcium Pantothenate, Biotin, Vitamin A, Thiamin Hydrochloride, Copper Sulfate, Riboflavin, Pyridoxine Hydrochloride, Sodium Selenate, Manganese Sulfate, Phylloquinone, Folic Acid, Vitamin D3, And Vitamin B12."
3,104,Bobbie,Grass-Fed Whole Milk\n(non-organic),ND,NT,ND,ND,ND,NaN,"7,080,000",ND,ND,ND,ND,2026,https://www.hibobbie.com/products/grass-fed-whole-milk-infant-formula-14-1oz?variant=42520514101333,"lactose, organic whole milk, organic linoleic sunflower oil, organic low erucic acid rapeseed oil, organic whey protein concentrate, organic high oleic sunflower oil, organic coconut oil, less than 2 % of: organic low erucic acid rapeseed lecithin, schizochytrium sp. oil*, mortierella alpina oil**, calcium carbonate, calcium phosphate, potassium chloride, sodium chloride, potassium citrate, l-carnitine, magnesium phosphate, calcium ascorbate, choline bitartrate, inositol, potassium iodide, ferrous sulfate, d-alpha tocopheryl acetate, zinc sulfate, vitamin c palmitate, niacinamide, calcium pantothenate, biotin, vitamin a, thiamin hydrochloride, copper sulfate, riboflavin, mixed tocopherols, pyridoxine hydrochloride, sodium selenate, manganese sulfate, phylloquinone, folic acid, vitamin d3, vitamin b12. * a source of docosahexaenoic acid (dha) ** a source of arachidonic acid (ara)"
4,105,Bobbie,Organic,ND,NT,1.2,ND,ND,1030,"6,740,000",ND,ND,ND,ND,2025,https://www.hibobbie.com/products/bobbie-organic-infant-formula?variant=42520534450261,"organic lactose, organic nonfat milk, organic high oleic (safflower or sunflower) oil, organic low erucic acid rapeseed oil, organic whey protein concentrate, organic coconut oil, organic linoleic (sunflower or safflower) oil, less than 1%: organic low erucic acid rapeseed lecithin, schizochytrium sp. oil; mortierella alpina oil;"" calcium phosphate, potassium citrate, sodium chloride, calcium carbonate, potassium hydroxide, potassium phosphate, magnesium chloride, potassium bicarbonate, ferrous sulfate, potassium chloride, zinc sulfate, cupric sulfate, manganese sulfate, potassium iodide, sodium selenite, choline bitartrate, ascorbic acid (vitamin c), ascorbyl palmitate, inositol, l-carnitine, mixed tocopherols concentrate, di-alpha tocopheryl acetate (vitamin e), niacinamide (vitamin b3), calcium pantothenate, vitamin a palmitate, riboflavin (vitamin b2), thiamine hydrochloride (vitamin b1), pyridoxine hydrochloride (vitamin b6), folic acid, phytonadione (vitamin k), biotin, cholecalciferol (vitamin d3), cyanocobalamin (vitamin b12).' '"

In [32]:
df.tail()

,index_100,brand,model,total_arsenic,inorganic_arsenic,lead,cadmium,mercury,aluminum,potassium,bisphenol_a,bisphenol_f,bisphenol_s,acrylamide,report_year,website_link,ingredient_list
85,186,Sprout Organics,Plant-Based,15.1,4.5,8.5,22.4,1.6,4463,"5,166,667",3,ND,ND,18,2026,https://sproutorganic.com.au/products/infant-formula,"Organic Hydrolysed Rice Starch, Organic Oil Blend (Organic Coconut Oil, Organic Canola Oil, Organic Sunflower Oil, emulsifier organic sunflower lecithin, antioxidant natural mixed tocopherols), Sprout Organic Protein Blend (Organic Sprouted Rice Protein, Organic Sprouted Pea Protein), Docosahexaenoic Acid (DHA from algae), Arachidonic Acid (ARA from fungal), Vitamins, Minerals & Amino Acid Mix (Potassium, Calcium, Chloride, Phosphorus, L-Lysine, Choline, Sodium, Inositol, Vitamin C, L-Tryptophan, L-Threonine, Magnesium, Iron, Niacin, L-carnitine, Zinc, Vitamin E, Pantothenic Acid, Vitamin A, Riboflavin, Copper, Thiamin, Vitamin B6, Folic Acid, Manganese, Vitamin K1, Iodine, Biotin, Selenium, Vitamin D2, Vitamin B12)."
86,187,Up&Up (Target),Hypoallergenic,7.4,5.9,2.1,ND,ND,448,"7,673,333",ND,ND,ND,ND,2026,https://www.target.com/p/non-gmo-hypoallergenic-powder-infant-formula-27-8oz-up-38-up-8482/-/A-85428762,"corn syrup solids, vegetable oils (palm olein, soy, coconut, high oleic (safflower or sunflower) oil), casein hydrolysate (from milk)+, modified corn starch, less than 2%: mortierella alpina oil, schizochytrium sp. oil, lactobacillus rhamnosus, beta-carotene, vitamin a palmitate, vitamin d3, vitamin e acetate, vitamin k1, thiamin hydrochloride, riboflavin, vitamin b6 hydrochloride, vitamin b12, niacinamide, folic acid, calcium pantothenate, biotin, ascorbic acid, choline bitartrate, inositol, calcium citrate, calcium hydroxide, calcium phosphate, magnesium chloride, ferrous sulfate, zinc sulfate, manganese sulfate, cupric sulfate, potassium iodide, sodium selenite, sodium citrate, potassium citrate, potassium chloride, potassium bicarbonate, l-cystine, l-tryptophan, taurine, l-carnitine, calcium carbonate, calcium chloride, potassium hydroxide, potassium phosphate, ascorbyl palmitate, mixed tocopherol concentrate. ‡a source of hypoallergenic protein *a source of arachidonic acid (ara) **a source of docosahexaenoic acid (dha)"
87,188,Up&Up (Target),Premium,ND,NT,ND,ND,ND,191,"7,005,000",ND,ND,ND,ND,2025,https://www.target.com/p/premium-powder-infant-formula-22-2oz-up-38-up-8482/-/A-87841478,"nonfat milk, lactose, vegetable oils (palm olein, soy, coconut, high oleic [safflower or sunflower] oil), whey protein concentrate, less than 1%: 2'-fucosyllactose (2'-fl)◊, mortierella alpina oil*, schizochytrium sp. oil**, soy lecithin, vitamin a palmitate, vitamin d3, vitamin e acetate, vitamin k ,, thiamine hydrochloride, riboflavin, vitamin b; hydrochloride, vitamin b12, niacinamide, folic acid, calcium pantothenate, biotin, ascorbic acid, choline bitartrate, inositol, calcium carbonate, calcium chloride, calcium hydroxide, magnesium chloride, ferrous sulfate, zinc sulfate, manganese sulfate, cupric sulfate, potassium bicarbonate, potassium iodide, potassium hydroxide, potassium phosphate, sodium selenite, sodium citrate, taurine, l-carnitine, beta-carotene, mixed tocopherol concentrate, ascorbyl palmitate, monoglycerides, nucleotides (cytidine-5'-monophosphate, disodium uridine-5'-monophosphate, adenosine-5'-monophosphate, disodium guanosine-5'-monophosphate)."
88,189,Up&Up (Target),Sensitivity Premium,5.7,5.0,1.8,ND,ND,1585,"5,593,333",ND,ND,ND,ND,2026,https://www.target.com/p/sensitivity-premium-infant-formula-with-iron-powder-22-5oz-up-38-up-8482/-/A-85428763,"corn syrup, milk protein isolate, high oleic (safflower or sunflower) oil, sucrose, soy oil, coconut oil, less than 2%: mortierella alpina oil *, schizochytrium sp. oil **, 2'-fucosyllactose (2'-fl)º, lacto-n-neotetraose (lnnt)0, lutein, calcium phosphate, potassium citrate, potassium chloride, sodium citrate, magnesium phosphate, ascorbic acid, calcium carbonate, ferrous sulfate, magnesium chloride, ascorbyl palmitate, choline bitartrate, taurine, inositol, vitamin e (di-alpha tocopheryl acetate), zinc sulfate, mixed tocopherol concentrate, l-carnitine, niacin (niacinamide), calcium pantothenate, vitamin a palmitate, cupric sulfate, thiamine hydrochloride, riboflavin, pyridoxine hydrochloride, beta-carotene, folic acid, manganese sulfate, potassium iodide, vitamin k (phytonadione), biotin, sodium selenite, vitamin d (cholecalciferol), cyanocobalamin, potassium hydroxide, potassium bicarbonate, sodium chloride, sodium phosphate, monoglycerides, soy lecithin, nucleotides (adenosine-5'-monophosphate, cytidine-5'-monophosphate, disodium guanosine-5'-monophosphate, disodium uridine-5'-monophosphate). contains milk and soy."
89,190,Up&Up (Target),Soy,6.7,5.3,3.4,4.6,ND,3680,"6,460,000",ND,ND,ND,ND,2025,https://www.target.com/p/soy-powder-infant-formula-36oz-up-38-up-8482/-/A-15118125,"corn syrup, soy protein isolate, palm olein, soy oil, coconut oil, high oleic (safflower or sunflower) oil, less than 2%: mortierella alpina oil*, schizochytrium sp. oil**, lutein, fructooligosaccharide, calcium phosphate, potassium citrate, potassium chloride, magnesium chloride, sodium citrate, ascorbic acid, choline bitartrate, l-methionine, taurine, ascorbyl palmitate, ferrous sulfate, inositol, mixed tocopherol concentrate, zinc sulfate, vitamin e (di-alpha tocopheryl acetate), l-carnitine, niacinamide, calcium pantothenate, cupric sulfate, thiamine hydrochloride, vitamin a palmitate, riboflavin, pyridoxine hydrochloride, folic acid, potassium iodide, potassium hydroxide, vitamin k (phytonadione), biotin, sodium selenite, beta-carotene, vitamin d (cholecalciferol), cyanocobalamin, monoglycerides, soy lecithin, tribasic calcium phosphate, calcium carbonate, manganese sulfate, potassium bicarbonate. * a source of arachidonic acid (ara) ** a source of docosahexaenoic acid (dha)"

## 7. add columns for palm_words, soy_words, has_palm_oil, has_soy

In [48]:
df = df.assign(
    palm_words=pd.Series(dtype="object"),
    soy_words=pd.Series(dtype="object"),
    has_palm_oil=pd.Series(dtype="boolean"),
    has_soy=pd.Series(dtype="boolean"),
)

In [34]:
pd.set_option("display.max_colwidth", None)
display(df.ingredient_list)

0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             recalled
1                                                                                                                                                                                                                                       Dairy-based blend (of which 29% is fermented) [Lactose (from milk), Vegetable oils (High oleic sunflower oil, Coconut oil, Rapeseed oil, Sunflower oil), Skimmed milk, Demineralised whey (from milk), Whey concentrate (from milk), Fish oil, Potassium citrate, Calcium carbonate, Magnesium chloride, Choline chloride, Calcium phosphate, Sodium citrate, Potassium chloride, Vitamin C, Emulsifier (Soy lecithin), Inositol, Antioxidant (Vitamin C), Pantothenic acid, Nicotinamide, Vitamin E, Thiamin, Riboflavin, Vitamin B₆, Potassium iodide, Folic acid, Vitamin K₁, Biotin, Vitamin B₁₂], Galacto-oligosaccharides (GOS) (from milk), Milk protein, Fructo-oligosaccharides (FOS), Oil from Mortierella Alpina, Sodium chloride, L-Tryptophan, Ferrous sulphate, Zinc sulphate, L-Carnitine, Copper sulphate, Vitamin A, Sodium selenite, Manganese sulphate, Vitamin D₃. Allergy Advice: For allergens, see ingredients in bold.
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Organic Lactose, Organic Nonfat Milk (Source Of A2 Proteins), Organic High Oleic Sunflower, Organic Soybean Oil, Organic Whey Protein Concentrate, Organic Coconut Oil, Less Than 2% Of: Organic Soy Lecithin, Calcium Carbonate, Calcium Phosphate, Sodium Chloride, Potassium Chloride, Potassium Citrate, Magnesium Phosphate, Choline Bitartrate, Calcium Ascorbate, Inositol, Ferrous Sulfate, D-Alpha Tocopheryl Acetate, Zinc Sulfate, Niacinamide, Calcium Pantothenate, Biotin, Vitamin A, Thiamin Hydrochloride, Copper Sulfate, Riboflavin, Pyridoxine Hydrochloride, Sodium Selenate, Manganese Sulfate, Phylloquinone, Folic Acid, Vitamin D3, And Vitamin B12.
3                                                                                                                                                                                                                                                          lactose, organic whole milk, organic linoleic sunflower oil, organic low erucic acid rapeseed oil, organic whey protein concentrate, organic high oleic sunflower oil, organic coconut oil, less than 2 % of: organic low erucic acid rapeseed lecithin, schizochytrium sp. oil*, mortierella alpina oil**, calcium carbonate, calcium phosphate, potassium chloride, sodium chloride, potassium citrate, l-carnitine, magnesium phosphate, calcium ascorbate, choline bitartrate, inositol, potassium iodide, ferrous sulfate, d-alpha tocopheryl acetate, zinc sulfate, vitamin c palmitate, niacinamide, calcium pantothenate, biotin, vitamin a, thiamin hydrochloride, copper sulfate, riboflavin, mixed tocopherols, pyridoxine hydrochloride, sodium selenate, manganese sulfate, phylloquinone, folic acid, vitamin d3, vitamin b12. * a source of docosahexaenoic acid (dha) ** a source of arachidonic acid (ara)
4                                                                                        organic lactose, organic nonfat milk, organic high oleic (safflower or sunflower) oil, organic low erucic acid rapeseed oil, organic whey protein concentrate, organic coconut oil, organic linoleic (sunflower or safflower) oil, less than 1%: organic low erucic acid rapeseed lecithin, schizochytrium sp. oil; mortierella alpina oil;" calcium phosphate, potassium citrate, sodium chloride, calcium carbonate, potassium hydroxide, potassium phosphate, magnesium chloride, potassium bicarbonate, ferrous sulfate, potassium chloride, zinc sulfate, cupric sulfate, manganese sulfate, potassium iodide, sodium selenite, choline bitartrate, ascorbic acid (vitamin c), ascorbyl palmitate, inositol, l-carnitine, mixed tocopherols concentrate, di-alpha tocopheryl acetate (vitamin e), niacinamide (vitamin b3), calcium pantothenate, vitamin a palmitate, riboflavin (vitamin b2), thiamine hydrochloride (vitamin b1), pyridoxine hydrochloride (vitamin b6), folic acid, phytonadione (vitamin k), biotin, cholecalciferol (vitamin d3), cyanocobalamin (vitamin b12).' '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...
85                                                                                                                                                                                                                                                                                                                                                                                                                              Organic Hydrolysed Rice Starch, Organic Oil Blend (Organic Coconut Oil, Organic Canola Oil, Organic Sunflower Oil, emulsifier organic sunflower lecithin, antioxidant natural mixed tocopherols), Sprout Organic Protein Blend (Organic Sprouted Rice Protein, Organic Sprouted Pea Protein), Docosahexaenoic Acid (DHA from algae), Arachidonic Acid (ARA from fungal), Vitamins, Minerals & Amino Acid Mix (Potassium, Calcium, Chloride, Phosphorus, L-Lysine, Choline, Sodium, Inositol, Vitamin C, L-Tryptophan, L-Threonine, Magnesium, Iron, Niacin, L-carnitine, Zinc, Vitamin E, Pantothenic Acid, Vitamin A, Riboflavin, Copper, Thiamin, Vitamin B6, Folic Acid, Manganese, Vitamin K1, Iodine, Biotin, Selenium, Vitamin D2, Vitamin B12).
86                                                                                                    corn syrup solids, vegetable oils (palm olein, soy, coconut, high oleic (safflower or sunflower) oil), casein hydrolysate (from milk)+, modified corn starch, less than 2%: mortierella alpina oil, schizochytrium sp. oil, lactobacillus rhamnosus, beta-carotene, vitamin a palmitate, vitamin d3, vitamin e acetate, vitamin k1, thiamin hydrochloride, riboflavin, vitamin b6 hydrochloride, vitamin b12, niacinamide, folic acid, calcium pantothenate, biotin, ascorbic acid, choline bitartrate, inositol, calcium citrate, calcium hydroxide, calcium phosphate, magnesium chloride, ferrous sulfate, zinc sulfate, manganese sulfate, cupric sulfate, potassium iodide, sodium selenite, sodium citrate, potassium citrate, potassium chloride, potassium bicarbonate, l-cystine, l-tryptophan, taurine, l-carnitine, calcium carbonate, calcium chloride, potassium hydroxide, potassium phosphate, ascorbyl palmitate, mixed tocopherol concentrate. ‡a source of hypoallergenic protein *a source of arachidonic acid (ara) **a source of docosahexaenoic acid (dha)
87                                                                                                                                                                nonfat milk, lactose, vegetable oils (palm olein, soy, coconut, high oleic [safflower or sunflower] oil), whey protein concentrate, less than 1%: 2'-fucosyllactose (2'-fl)◊, mortierella alpina oil*, schizochytrium sp. oil**, soy lecithin, vitamin a palmitate, vitamin d3, vitamin e acetate, vitamin k ,, thiamine hydrochloride, riboflavin, vitamin b; hydrochloride, vitamin b12, niacinamide, folic acid, calcium pantothenate, biotin, ascorbic acid, choline bitartrate, inositol, calcium carbonate, calcium chloride, calcium hydroxide, magnesium chloride, ferrous sulfate, zinc sulfate, manganese sulfate, cupric sulfate, potassium bicarbonate, potassium iodide, potassium hydroxide, potassium phosphate, sodium selenite, sodium citrate, taurine, l-carnitine, beta-carotene, mixed tocopherol concentrate, ascorbyl palmitate, monoglycerides, nucleotides (cytidine-5'-monophosphate, disodium uridine-5'-monophosphate, adenosine-5'-monophosphate, disodium guanosine-5'-monophosphate).
88    corn syrup, milk protein isolate, high oleic (safflower or sunflower) oil, sucrose, soy oil, coconut oil, less than 2%: mortierella alpina oil *, schizochytrium sp. oil **, 2'-fucosyllactose (2'-fl)º, lacto-n-neotetraose (lnnt)0, lutein, calcium phosphate, potassium citrate, potassium chloride, sodium citrate, magnesium phosphate, ascorbic acid, calcium carbonate, ferrous sulfate, magnesium chloride, ascorbyl palmitate, choline bitartrate, taurine, inositol, vitamin e (di-alpha tocopheryl acetate), zinc sulfate, mixed tocopherol concentrate, l-carnitine, niacin (niacinamide), calcium pantothenate, vitamin a palmitate, cupric sulfate, thiamine hydrochloride, riboflavin, pyridoxine hydrochloride, beta-carotene, folic acid, manganese sulfate, potassium iodide, vitamin k (phytonadione), biotin, sodium selenite, vitamin d (cholecalciferol), cyanocobalamin, potassium hydroxide, potassium bicarbonate, sodium chloride, sodium phosphate, monoglycerides, soy lecithin, nucleotides (adenosine-5'-monophosphate, cytidine-5'-monophosphate, disodium guanosine-5'-monophosphate, disodium uridine-5'-monophosphate). contains milk and soy.
89                                                                                                                                                  corn syrup, soy protein isolate, palm olein, soy oil, coconut oil, high oleic (safflower or sunflower) oil, less than 2%: mortierella alpina oil*, schizochytrium sp. oil**, lutein, fructooligosaccharide, calcium phosphate, potassium citrate, potassium chloride, magnesium chloride, sodium citrate, ascorbic acid, choline bitartrate, l-methionine, taurine, ascorbyl palmitate, ferrous sulfate, inositol, mixed tocopherol concentrate, zinc sulfate, vitamin e (di-alpha tocopheryl acetate), l-carnitine, niacinamide, calcium pantothenate, cupric sulfate, thiamine hydrochloride, vitamin a palmitate, riboflavin, pyridoxine hydrochloride, folic acid, potassium iodide, potassium hydroxide, vitamin k (phytonadione), biotin, sodium selenite, beta-carotene, vitamin d (cholecalciferol), cyanocobalamin, monoglycerides, soy lecithin, tribasic calcium phosphate, calcium carbonate, manganese sulfate, potassium bicarbonate. * a source of arachidonic acid (ara) ** a source of docosahexaenoic acid (dha)
Name: ingredient_list, Length: 90, dtype: str

## 8. Check the length of each entry in ingredient_list to ensure that the ingredients are correctly parsed

In [35]:
for i in range(len(df.ingredient_list)):
    print(df.brand[i],df.model[i],len(df.ingredient_list[i]))

A2 Platinum 8
Aptamil First Infant Milk 910
Baby’s Only
Organic Complete Nutrition 652
Bobbie Grass-Fed Whole Milk
(non-organic) 891
Bobbie Organic 1053
Bobbie Organic Gentle 1155
Bobbie Organic Whole Milk 819
Bubs Stage 1 Easy-digest
Goat Milk 918
Bubs Stage 1 Organic
Grass Fed 835
ByHeart Whole Nutrition 1084
Dr. Brown’s GentlePro 1004
Dr. Brown’s Good Start Soy-Ease Pro 931
Dr. Brown’s SoothePro 1019
Earth’s Best Organic Dairy 1156
Earth’s Best Organic Sensitivity 1154
EleCare Hypoallergenic 976
Enfamil 24 Ready to Feed 980
Enfamil A.R. 730
Enfamil Concentrated 936
Enfamil Enspire Optimum 774
Enfamil Gentlease 739
Enfamil Infant Formula 858
Enfamil NeuroPro 781
Enfamil NeuroPro EnfaCare Ready
to Feed 905
Enfamil NeuroPro Enfacare 883
Enfamil NeuroPro Gentlease 813
Enfamil NeuroPro Gentlease Ready
to Feed 921
Enfamil NeuroPro Ready to Feed 845
Enfamil Nutramigen 822
Enfamil Nutramigen Ready to Feed 776
Enfamil Nutramigen with Probiotic
LGG 822
Enfamil Optimum Ready to Feed 825
Enfamil Pregestimil Hypoallergenic
Infant Formula for Fat Mal-
absorption Ready to Feed 788
Enfamil ProSobee Simply
Plant-Based 685
Enfamil ProSobee Simply Plant-
Based 685
Enfamil Reguline 786
Enfamil Sensitive 697
Happy Baby
Organics Organic Infant Formula 884
Happy Baby
Organics Sensitive 1083
HiPP Dutch Organic Stage 1 814
HiPP Hypoallergenic 790
HiPP Organic Whole Milk Ready
to Feed 616
Holle Bio Organic Stage 1 688
Holle Organic Goat Milk 619
Jovie Stage 1 Organic Goat Milk 764
Kabrita Goat Milk-Based 798
Kendamil First Infant Milk Ready to
Feed 997
Kendamil Goat 945
Kendamil Organic 925
Kendamil Whole Milk 1029
Kirkland
Signature (Costco) ProCare 1199
Mama Bear Sensitivity Premium 1233
Member’s Mark
(Sam’s Club) Advantage Premium 1116
Nannycare Goat milk based 821
Neocate Hypoallergenic 1420
Neocate Syneo Hypoallergenic 1463
Nestle Alfamino 1099
Nestle Extensive HA 1046
Nutricia Fortini Milk-Based with Iron Ready
to Feed 1182
Parent’s Choice Advantage Premium 1159
Parent’s Choice Infant 1143
Parent’s Choice Sensitivity Premium 1233
Pepticate Hypoallergenic 1019
PurAmino Hypoallergenic 937
Pure Bliss by
Similac Irish Farms 916
Pure Goat Bio Complete 795
Similac 360 Total Care 1033
Similac 360 Total Care
Sensitive 1036
Similac 360 Total Care Ready to
Feed 1032
Similac 360 Total Care Sensitive
Ready to Feed 1037
Similac Advance 937
Similac Advance Concentrated 926
Similac Advance Ready to Feed 936
Similac Alimentum 890
Similac Alimentum Ready to Feed 874
Similac NeoSure 947
Similac NeoSure Ready to Feed 957
Similac Pro-Total Comfort Ready to
Feed 969
Similac Pure Bliss Ready to Feed 897
Similac Sensitive 951
Similac Sensitive Ready to Feed 952
Similac Soy Isomil 761
Similac Soy Isomil Concentrated 797
Similac Soy Isomil Ready to Feed 807
Similac Total Comfort 991
Sprout Organics Plant-Based 726
Up&Up (Target) Hypoallergenic 1040
Up&Up (Target) Premium 980
Up&Up (Target) Sensitivity Premium 1136
Up&Up (Target) Soy 994

# 9. Get the list of words in the ingredient_list that have 'palm' or 'soy' for classification. 

We will use this list to identify if the formula has palm or soy ingredients. A simple way to do so is to split on commas and parentheses

In [55]:
def extract_terms(text):
    """
    Split ingredient text on commas and parentheses/brackets.
    Returns a list of cleaned terms.
    """

    if not isinstance(text, str):
        return []

    terms = re.split(r"[,()\[\]]", text)

    return [
        term.strip(" .;:").lower()
        for term in terms
        if term.strip()
    ]

In [56]:
df["ingredient_array"] = df["ingredient_list"].apply(extract_terms)

In [57]:
df.head()

,index_100,brand,model,total_arsenic,inorganic_arsenic,lead,cadmium,mercury,aluminum,potassium,...,bisphenol_s,acrylamide,report_year,website_link,ingredient_list,palm_words,soy_words,has_palm_oil,has_soy,ingredient_array
0,101,A2,Platinum,ND,NT,2.9,ND,ND,1770,"5,580,000",...,ND,ND,2025,https://a2platinum.com/pages/why-a2,recalled,NaN,NaN,<NA>,<NA>,[recalled]
1,102,Aptamil,First Infant Milk,ND,NT,1.5,ND,ND,215,"5,670,000",...,ND,ND,2025,https://www.nutricia.co.uk/hcp/pim-products/aptamil-first-infant-milk-with-pronutra-powder.html,"Dairy-based blend (of which 29% is fermented) [Lactose (from milk), Vegetable oils (High oleic sunflower oil, Coconut oil, Rapeseed oil, Sunflower oil), Skimmed milk, Demineralised whey (from milk), Whey concentrate (from milk), Fish oil, Potassium citrate, Calcium carbonate, Magnesium chloride, Choline chloride, Calcium phosphate, Sodium citrate, Potassium chloride, Vitamin C, Emulsifier (Soy lecithin), Inositol, Antioxidant (Vitamin C), Pantothenic acid, Nicotinamide, Vitamin E, Thiamin, Riboflavin, Vitamin B₆, Potassium iodide, Folic acid, Vitamin K₁, Biotin, Vitamin B₁₂], Galacto-oligosaccharides (GOS) (from milk), Milk protein, Fructo-oligosaccharides (FOS), Oil from Mortierella Alpina, Sodium chloride, L-Tryptophan, Ferrous sulphate, Zinc sulphate, L-Carnitine, Copper sulphate, Vitamin A, Sodium selenite, Manganese sulphate, Vitamin D₃. Allergy Advice: For allergens, see ingredients in bold.",NaN,NaN,<NA>,<NA>,"[dairy-based blend, of which 29% is fermented, lactose, from milk, vegetable oils, high oleic sunflower oil, coconut oil, rapeseed oil, sunflower oil, skimmed milk, demineralised whey, from milk, whey concentrate, from milk, fish oil, potassium citrate, calcium carbonate, magnesium chloride, choline chloride, calcium phosphate, sodium citrate, potassium chloride, vitamin c, emulsifier, soy lecithin, inositol, antioxidant, vitamin c, pantothenic acid, nicotinamide, vitamin e, thiamin, riboflavin, vitamin b₆, potassium iodide, folic acid, vitamin k₁, biotin, vitamin b₁₂, galacto-oligosaccharides, gos, from milk, milk protein, fructo-oligosaccharides, fos, oil from mortierella alpina, sodium chloride, l-tryptophan, ferrous sulphate, zinc sulphate, l-carnitine, copper sulphate, vitamin a, sodium selenite, manganese sulphate, vitamin d₃. allergy advice: for allergens, see ingredients in bold]"
2,103,Baby’s Only\nOrganic,Complete Nutrition,ND,NT,1.4,ND,ND,307,"6,080,000",...,ND,ND,2025,https://babysonly.com/collections/shop-all/products/organic-gentle-infant-formula,"Organic Lactose, Organic Nonfat Milk (Source Of A2 Proteins), Organic High Oleic Sunflower, Organic Soybean Oil, Organic Whey Protein Concentrate, Organic Coconut Oil, Less Than 2% Of: Organic Soy Lecithin, Calcium Carbonate, Calcium Phosphate, Sodium Chloride, Potassium Chloride, Potassium Citrate, Magnesium Phosphate, Choline Bitartrate, Calcium Ascorbate, Inositol, Ferrous Sulfate, D-Alpha Tocopheryl Acetate, Zinc Sulfate, Niacinamide, Calcium Pantothenate, Biotin, Vitamin A, Thiamin Hydrochloride, Copper Sulfate, Riboflavin, Pyridoxine Hydrochloride, Sodium Selenate, Manganese Sulfate, Phylloquinone, Folic Acid, Vitamin D3, And Vitamin B12.",NaN,NaN,<NA>,<NA>,"[organic lactose, organic nonfat milk, source of a2 proteins, organic high oleic sunflower, organic soybean oil, organic whey protein concentrate, organic coconut oil, less than 2% of: organic soy lecithin, calcium carbonate, calcium phosphate, sodium chloride, potassium chloride, potassium citrate, magnesium phosphate, choline bitartrate, calcium ascorbate, inositol, ferrous sulfate, d-alpha tocopheryl acetate, zinc sulfate, niacinamide, calcium pantothenate, biotin, vitamin a, thiamin hydrochloride, copper sulfate, riboflavin, pyridoxine hydrochloride, sodium selenate, manganese sulfate, phylloquinone, folic acid, vitamin d3, and vitamin b12]"
3,104,Bobbie,Grass-Fed Whole Milk\n(non-organic),ND,NT,ND,ND,ND,NaN,"7,080,000",...,ND,ND,2026,https://www.hibobbie.com/products/grass-fed-whole-milk-infant-formula-14-1oz?variant=42520514101333,"lactose, organic whole milk, organic linoleic sunflower oil, organic low erucic acid rapeseed oil, organic whey protein concentrate, organic high oleic sunflower oil, organic coconut oil, less than 2 % of: organic low erucic acid rapeseed lecithin, schizochytrium sp. oil*, mortierella alpina oil**, calcium carbonate, calcium phosphate, potassium chloride, sodium chloride, potassium citrate, l-carnitine, magnesium phosphate, calcium ascorbate, choline bitartrate, inositol, potassium iodide, ferrous sulfate, d-alpha tocopheryl acetate, zinc sulfate, vitamin c palmitate, niacinamide, calcium pantothenate, biotin, vitamin a, thiamin hydrochloride, copper sulfate, riboflavin, mixed tocopherols, pyridoxine hydrochloride, sodium selenate, manganese sulfate, phylloquinone, folic acid, vitamin d3, vitamin b12. * a source of docosahexaenoic acid (dha) ** a source of arachidonic acid (ara)",NaN,NaN,<NA>,<NA>,"[lactose, organic whole milk, organic linoleic sunflower oil, organic low erucic acid rapeseed oil, organic whey protein concentrate, organic high oleic sunflower oil, organic coconut oil, less than 2 % of: organic low erucic acid rapeseed lecithin, schizochytrium sp. oil*, mortierella alpina oil**, calcium carbonate, calcium phosphate, potassium chloride, sodium chloride, potassium citrate, l-carnitine, magnesium phosphate, calcium ascorbate, choline bitartrate, inositol, potassium iodide, ferrous sulfate, d-alpha tocopheryl acetate, zinc sulfate, vitamin c palmitate, niacinamide, calcium pantothenate, biotin, vitamin a, thiamin hydrochloride, copper sulfate, riboflavin, mixed tocopherols, pyridoxine hydrochloride, sodium selenate, manganese sulfate, phylloquinone, folic acid, vitamin d3, vitamin b12. * a source of docosahexaenoic acid, dha, ** a source of arachidonic acid, ara]"
4,105,Bobbie,Organic,ND,NT,1.2,ND,ND,1030,"6,740,000",...,ND,ND,2025,https://www.hibobbie.com/products/bobbie-organic-infant-formula?variant=42520534450261,"organic lactose, organic nonfat milk, organic high oleic (safflower or sunflower) oil, organic low erucic acid rapeseed oil, organic whey protein concentrate, organic coconut oil, organic linoleic (sunflower or safflower) oil, less than 1%: organic low erucic acid rapeseed lecithin, schizochytrium sp. oil; mortierella alpina oil;"" calcium phosphate, potassium citrate, sodium chloride, calcium carbonate, potassium hydroxide, potassium phosphate, magnesium chloride, potassium bicarbonate, ferrous sulfate, potassium chloride, zinc sulfate, cupric sulfate, manganese sulfate, potassium iodide, sodium selenite, choline bitartrate, ascorbic acid (vitamin c), ascorbyl palmitate, inositol, l-carnitine, mixed tocopherols concentrate, di-alpha tocopheryl acetate (vitamin e), niacinamide (vitamin b3), calcium pantothenate, vitamin a palmitate, riboflavin (vitamin b2), thiamine hydrochloride (vitamin b1), pyridoxine hydrochloride (vitamin b6), folic acid, phytonadione (vitamin k), biotin, cholecalciferol (vitamin d3), cyanocobalamin (vitamin b12).' '",NaN,NaN,<NA>,<NA>,"[organic lactose, organic nonfat milk, organic high oleic, safflower or sunflower, oil, organic low erucic acid rapeseed oil, organic whey protein concentrate, organic coconut oil, organic linoleic, sunflower or safflower, oil, less than 1%: organic low erucic acid rapeseed lecithin, schizochytrium sp. oil; mortierella alpina oil;"" calcium phosphate, potassium citrate, sodium chloride, calcium carbonate, potassium hydroxide, potassium phosphate, magnesium chloride, potassium bicarbonate, ferrous sulfate, potassium chloride, zinc sulfate, cupric sulfate, manganese sulfate, potassium iodide, sodium selenite, choline bitartrate, ascorbic acid, vitamin c, ascorbyl palmitate, inositol, l-carnitine, mixed tocopherols concentrate, di-alpha tocopheryl acetate, vitamin e, niacinamide, vitamin b3, calcium pantothenate, vitamin a palmitate, riboflavin, vitamin b2, thiamine hydrochloride, vitamin b1, pyridoxine hydrochloride, vitamin b6, folic acid, phytonadione, vitamin k, biotin, cholecalciferol, vitamin d3, cyanocobalamin, vitamin b12, ' ']"

# 10. Test logic to see how how it handles parentheses and commas in the ingredient_list
Using Aptamil (index = 1, i.e. iloc[1] as an example)

In [59]:
print(el for el in df.ingredient_array.iloc[1])

<generator object <genexpr> at 0x149abe330>

None

In [60]:
for el in df["ingredient_array"].iloc[1]:
    print(el)

dairy-based blend
of which 29% is fermented
lactose
from milk
vegetable oils
high oleic sunflower oil
coconut oil
rapeseed oil
sunflower oil
skimmed milk
demineralised whey
from milk
whey concentrate
from milk
 fish oil
potassium citrate
calcium carbonate
magnesium chloride
choline chloride
calcium phosphate
sodium citrate
potassium chloride
vitamin c
emulsifier
soy lecithin
inositol
antioxidant
vitamin c
pantothenic acid
nicotinamide
vitamin e
thiamin
riboflavin
vitamin b₆
potassium iodide
folic acid
vitamin k₁
biotin
vitamin b₁₂
galacto-oligosaccharides
gos
from milk
 milk protein
fructo-oligosaccharides
fos
oil from mortierella alpina
sodium chloride
l-tryptophan
ferrous sulphate
zinc sulphate
l-carnitine
copper sulphate
vitamin a
sodium selenite
manganese sulphate
vitamin d₃. allergy advice: for allergens
see ingredients in bold

# 11. Identify ingredient words with "palm" and "soy" to ascertain if the formula has soy or palm oil in it.

In [65]:
df["soy_words"] = df["ingredient_array"].apply(
    lambda ingredients: [
        item for item in ingredients
        if "soy" in item.lower()
    ]
)

In [67]:
df["palm_words"] = df["ingredient_array"].apply(
    lambda ingredients: [
        item for item in ingredients
        if "palm" in item.lower()
    ]
)

In [70]:
palm_counts = (
    df["palm_words"]
    .explode()              # turns lists into individual rows
    .dropna()
    .value_counts()
)

print(palm_counts)

palm_words
vitamin a palmitate                                      53
ascorbyl palmitate                                       36
contains one or more of the following: palm olein oil    12
palm olein                                               11
 vitamin a palmitate                                      7
palm oil                                                  3
vitamin c palmitate                                       2
organic palm oil                                          2
palm kernel and/or coconut oil                            2
and high 2-palmitic vegetable oil                         2
sustainable palm olein                                    1
organic palm or palm olein                                1
organic palm oil or palm olein                            1
palm olein oil                                            1
retinyl palmitate                                         1
organic palm olein or palm oil                            1
palm oil*³                                                1
high 2-palmitic acid vegetable oil                        1
vitamin a palmitate*                                      1
palm                                                      1
l-ascorbyl 6-palmitate                                    1
Name: count, dtype: int64

In [72]:
palm_counts.dtypes

dtype('int64')

In [74]:
soy_counts = (
    df["soy_words"]
    .explode()              # turns lists into individual rows
    .dropna()
    .value_counts()
)

print(soy_counts)

soy_words
soy oil                                                                                   43
soy lecithin                                                                              34
soy                                                                                       15
 soy lecithin                                                                              6
soy protein isolate                                                                        5
organic soy lecithin                                                                       5
 soy protein isolate                                                                       2
organic soy oil                                                                            2
contains milk and soy. ◊ sources of prebiotic *a source of arachidonic acid                2
soy lecithin                                                                               1
organic soybean oil                                                                        1
less than 2% of: organic soy lecithin                                                      1
soybean lecithin                                                                           1
organic soy                                                                                1
 organic soy oil                                                                           1
soy and high oleic sunflower oils                                                          1
 soy oil                                                                                   1
soybean oil                                                                                1
soybean oil*                                                                               1
soy lecithin*                                                                              1
contains milk and soy. #sources of prebiotic *a source of arachidonic acid                 1
soybean                                                                                    1
contains milk and soy ingredients. *a type of prebiotic **a source of arachidonic acid     1
contains milk and soy. *a source of arachidonic acid                                       1
contains milk and soy                                                                      1
Name: count, dtype: int64

# 12. Get list of of words to exclude from the list of ingredients containing palm oil as false positives. Use this to build out s
E.g. ascorbyl palmitate is a source of vitamin C. It's not a palm oil containing ingredient like palm olein. So we need to exclude ingredients containing these words so we don't incorrectly mark these formulas as containing palm oil.

In [84]:
exclude_terms = [
    "vitamin",
    "ascorb", ## vitamin C is ascorbic acid, e.g. added as ascorbyl palmitate
    "retin", ## vitamin A is retinol, e.g. added as retinyl palmitate
]

for word, count in palm_counts.items():

    flag = int(
        not any(term in word for term in exclude_terms)
    )

    print(word, flag)

vitamin a palmitate 0
ascorbyl palmitate 0
contains one or more of the following: palm olein oil 1
palm olein 1
 vitamin a palmitate 0
palm oil 1
vitamin c palmitate 0
organic palm oil 1
palm kernel and/or coconut oil 1
and high 2-palmitic vegetable oil 1
sustainable palm olein 1
organic palm or palm olein 1
organic palm oil or palm olein 1
palm olein oil 1
retinyl palmitate 0
organic palm olein or palm oil 1
palm oil*³ 1
high 2-palmitic acid vegetable oil 1
vitamin a palmitate* 0
palm 1
l-ascorbyl 6-palmitate 0